apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-notebook-pv
spec:
  capacity:
    storage: 10MB
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # We want to retain our data