apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-notebook-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5MB


#Pods use PersistentVolumeClaims to request physical storage
